[package]
name = "permission_tokens"
version = "2.0.0-pre-rc.3"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_permissions_validators = { path = "../../permissions_validators" }
iroha_schema = { path = "../../schema" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
